### ISSUE TITLE
[Teamserver-Client--Bug]: Teamserver。Quit directly without exception

### ISSUE THREAD

**Issue by badboycxcc** [HavocFramework/Havoc#201]
### Contact Details

cxaqhq@gmail.com

### What happened?

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa5ae3c]

goroutine 16 [running]:
Havoc/pkg/teamserver.(*Teamserver).SendEvent(0xc00026cb40, {0xc0003884e6, 0x6}, {{0x7, {0x0, 0x0}, {0xc0002662d0, 0x13}, {0x0, 0x0}}, ...})
        /root/Havoc/Teamserver/pkg/teamserver/teamserver.go:405 +0x1dc
Havoc/pkg/teamserver.(*Teamserver).EventBroadcast(0xc00026cb40, {0x0, 0x0}, {{0x7, {0x0, 0x0}, {0xc0002662d0, 0x13}, {0x0, 0x0}}, ...})
        /root/Havoc/Teamserver/pkg/teamserver/teamserver.go:383 +0x133
Havoc/pkg/teamserver.(*Teamserver).ListenerStart.func8({0xc000388a40, 0x8}, {0xc0001880b0, 0x2})
        /root/Havoc/Teamserver/pkg/teamserver/listener.go:154 +0x198
Havoc/pkg/agent.(*Agent).BackgroundUpdateLastCallbackUI(0xc00009e420, {0xc0003b0ca0, 0x0, 0xc0003b0ce0, 0xc0003b0c30, 0xc0003b0c40, 0xc0003889c0, 0xc0003b0c50, 0xc0003b0c60, 0xc0003889d0, ...})
        /root/Havoc/Teamserver/pkg/agent/agent.go:552 +0x103
created by Havoc/pkg/handlers.(*HTTP).request
        /root/Havoc/Teamserver/pkg/handlers/http.go:256 +0x96b

### Did You Do a Pull First?

Latest (You performed a pull first)

### Relevant log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa5ae3c]

goroutine 16 [running]:
Havoc/pkg/teamserver.(*Teamserver).SendEvent(0xc00026cb40, {0xc0003884e6, 0x6}, {{0x7, {0x0, 0x0}, {0xc0002662d0, 0x13}, {0x0, 0x0}}, ...})
        /root/Havoc/Teamserver/pkg/teamserver/teamserver.go:405 +0x1dc
Havoc/pkg/teamserver.(*Teamserver).EventBroadcast(0xc00026cb40, {0x0, 0x0}, {{0x7, {0x0, 0x0}, {0xc0002662d0, 0x13}, {0x0, 0x0}}, ...})
        /root/Havoc/Teamserver/pkg/teamserver/teamserver.go:383 +0x133
Havoc/pkg/teamserver.(*Teamserver).ListenerStart.func8({0xc000388a40, 0x8}, {0xc0001880b0, 0x2})
        /root/Havoc/Teamserver/pkg/teamserver/listener.go:154 +0x198
Havoc/pkg/agent.(*Agent).BackgroundUpdateLastCallbackUI(0xc00009e420, {0xc0003b0ca0, 0x0, 0xc0003b0ce0, 0xc0003b0c30, 0xc0003b0c40, 0xc0003889c0, 0xc0003b0c50, 0xc0003b0c60, 0xc0003889d0, ...})
        /root/Havoc/Teamserver/pkg/agent/agent.go:552 +0x103
created by Havoc/pkg/handlers.(*HTTP).request
        /root/Havoc/Teamserver/pkg/handlers/http.go:256 +0x96b
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Thanks for opening this issue. I am going to investigate this issue and try to commit a fix in the next update.

**Comment by Cracked5pider** [comment]
I commited a fix. try it again and let me know if its still doesnt work

**Comment by badboycxcc** [comment]
OK, I need to recompile it.

**Comment by badboycxcc** [comment]
2022/10/31 12:32:12 http: panic serving 192.168.1.88:55627: runtime error: invalid memory address or nil pointer dereference
goroutine 44153 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/go-1.19/src/net/http/server.go:1850 +0xbf
panic({0xb16d20, 0x10d7020})
        /usr/lib/go-1.19/src/runtime/panic.go:890 +0x262
Havoc/pkg/teamserver.(*Teamserver).SendEvent(0xc00026cb40, {0xc0002a788a, 0x6}, {{0x7, {0x0, 0x0}, {0xc000372480, 0x13}, {0x0, 0x0}}, ...})
        /root/Havoc/Teamserver/pkg/teamserver/teamserver.go:405 +0x1dc
Havoc/pkg/teamserver.(*Teamserver).EventBroadcast(0xc00026cb40, {0x0, 0x0}, {{0x7, {0x0, 0x0}, {0xc000372480, 0x13}, {0x0, 0x0}}, ...})
        /root/Havoc/Teamserver/pkg/teamserver/teamserver.go:383 +0x133
Havoc/pkg/teamserver.(*Teamserver).ListenerStart.func8({0xc0002a6d90, 0x8}, {0xc0002a7b80, 0x2})
        /root/Havoc/Teamserver/pkg/teamserver/listener.go:154 +0x198
Havoc/pkg/agent.(*Agent).UpdateLastCallback(0xc00009e4d0, {0xc0003aead0, 0x0, 0xc0003aeb10, 0xc0003aea60, 0xc0003aea70, 0xc0003907c0, 0xc0003aea80, 0xc0003aea90, 0xc0003907d0, ...})
        /root/Havoc/Teamserver/pkg/agent/agent.go:524 +0x14e
Havoc/pkg/agent.(*Agent).TaskDispatch(0xc00009e4d0, 0x63, 0xc0003b9fc0, {0xc0003aead0, 0x0, 0xc0003aeb10, 0xc0003aea60, 0xc0003aea70, 0xc0003907c0, 0xc0003aea80, ...})
        /root/Havoc/Teamserver/pkg/agent/demons.go:1257 +0x105
Havoc/pkg/handlers.(*HTTP).request(0xc000312fc0, 0xc000374500)
        /root/Havoc/Teamserver/pkg/handlers/http.go:231 +0x785
github.com/gin-gonic/gin.(*Context).Next(...)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0000b3860, 0xc000374500)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555 +0x671
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0000b3860, {0xd0f128?, 0xc000257260}, 0xc00021a100)
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 +0x1d2
net/http.serverHandler.ServeHTTP({0xd0d568?}, {0xd0f128, 0xc000257260}, 0xc00021a100)
        /usr/lib/go-1.19/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc000176a00, {0xd0fc38, 0xc00007fa70})
        /usr/lib/go-1.19/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        /usr/lib/go-1.19/src/net/http/server.go:3102 +0x4db
[ERRO] error while sending info to client(e0e8ab):  writev tcp 192.168.1.100:55554->192.168.1.120:14066: writev: broken pipe
[WARN] User <cxaqhq> Disconnected

**Comment by badboycxcc** [comment]
Now the program is running, but I can't control it. I'm sure it's online.

**Comment by badboycxcc** [comment]
![img_v2_f1c5d043-d267-4ed0-8f20-bd2d7e6e837g](https://user-images.githubusercontent.com/72059221/199166018-2b291496-83dd-4831-9251-34997510338d.jpg)
